from typing import TypedDict, Annotated, List, Dict, Any
from langgraph.graph.message import add_messages
from langchain_core.messages import BaseMessage

class AgentState(TypedDict):
    """
    The state passed between our Gemini AI and the Docker sandbox.
    """
    # Automatically appends new messages to the chat history
    messages: Annotated[List[BaseMessage], add_messages]
    
    # The raw Python code generated by the LLM
    current_code: str
    
    # The output from sandbox.py (success status, stdout, stderr)
    sandbox_result: Dict[str, Any]
    
    # Counter to prevent infinite loops (stopping after 3 failed attempts)
    iterations: int